"use client";
import { useEffect, useState } from 'react';
import { Download, History } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { readExports, type ExportRecord } from '@/lib/eves/export-history';
import { downloadBlob } from '@/lib/eves/export';
import { toast } from 'sonner';
export function ExportHistory({ scope, revision, onCreate }: { scope: string; revision: number; onCreate: () => void }) {
  const [records, setRecords] = useState<ExportRecord[]>([]);
  const [status, setStatus] = useState('loading');
  const [retry, setRetry] = useState(0);
  useEffect(() => {
    let live = true;
    setStatus('loading'); setRecords([]);
    readExports(scope).then(records => { if (live) { setRecords(records); setStatus('ready'); } }).catch(() => { if (live) setStatus('error'); });
    return () => { live = false; };
  }, [scope, revision, retry]);
  return <section className="panel p-6 space-y-5" aria-label="Export history">
    <div><h2 className="text-lg font-semibold">Export history</h2><p className="mt-1 text-sm text-muted-foreground">Exports generated in this browser for the current tenant and data source. Files are saved on this device; clearing browser data removes them.</p></div>
    {status === 'loading' ? <p role="status">Loading exports…</p> : status === 'error' ? <div role="alert"><p>Export history could not be opened. Allow browser storage and try again.</p><Button className="mt-3" variant="outline" onClick={() => setRetry(v => v+1)}>Try again</Button></div> : !records.length ? <div className="py-10 text-center"><History className="mx-auto mb-3 size-8 text-primary" /><h3 className="font-medium">No exports yet</h3><p className="mt-2 text-sm text-muted-foreground">Generate a downloadable report to save it here.</p><Button className="mt-4" onClick={onCreate}>Create report</Button></div> : <div className="divide-y">{records.map(record => <article key={record.id} className="flex flex-wrap items-center justify-between gap-4 py-5">
      <div className="min-w-0"><p className="text-xs text-muted-foreground">{new Date(record.createdAt).toLocaleString()}</p><h3 className="mt-1 font-semibold">{record.agency} — {record.period}</h3><p className="mt-1 text-sm text-muted-foreground">{record.reports.length} reports · {record.records} records · {record.source === 'sample' ? 'Sample data' : 'Workspace data'}</p><p className="mt-1 text-xs text-muted-foreground">Generated by {record.generatedBy}</p><details className="mt-2 text-sm"><summary className="cursor-pointer text-primary">View export details</summary><ul className="mt-2 list-disc pl-5">{record.reports.map(name => <li key={name}>{name}</li>)}</ul><p className="mt-2 break-all text-xs">{record.filename}</p><p className="mt-1 text-xs text-muted-foreground">Working export. Agency validation and submission are not tracked.</p></details></div>
      <div className="flex items-center gap-3"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">Generated</span><Button variant="outline" onClick={() => { try { downloadBlob(record.blob, record.filename); } catch { toast.error('Download failed. Please try again.'); } }}><Download size={16} />Download</Button></div>
    </article>)}</div>}
  </section>;
}
